name=BitflashRobotics
version=1.0.0
author=iceches
sentence=BFR provisions and protocol.
paragraph=Provides the BFR communication protocol and definitions.
category=Data Processing
url=https://github.com/iceches/BitflashRobotics
architectures=*
includes=bfr_provisions.h
depends=
